lista_goala = []
print(len(lista_goala))
lista_cu_elemente = [1, 2, 3]
print(lista_cu_elemente[0])
print(len(lista_cu_elemente))
lista_goala.append(4)
print(lista_goala)
lista_goala.clear()
print(lista_goala)
lista_goala = lista_cu_elemente.copy()
print(lista_goala)
lista_cu_elemente.extend(lista_goala)
print(lista_cu_elemente)
print(lista_cu_elemente.count(1))
print(lista_cu_elemente.index(1))
lista_cu_elemente.remove(1)
print(lista_cu_elemente)
lista_cu_elemente.insert(1,1)
print(lista_cu_elemente)
lista_cu_elemente.pop(1)
print(lista_cu_elemente)
lista_cu_elemente.reverse()
print(lista_cu_elemente)
lista_cu_elemente.sort()
print(lista_cu_elemente)
print(min(lista_cu_elemente))
